spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  application:
    name: task-manager
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: task-manager:${random.numer}
server:
  port: 8080
